name: Snyk - Software Bill of Materials (SBOM)
on:
  push:
  release:
    types: [published]

jobs:
  sbom:
    permissions:
      contents: write
    uses: enzowritescode/reusable-actions/.github/workflows/snyk-sbom.yml@a74971e05347d597a8052792de93972d92197981 # mobile branch
    secrets: inherit
    with:
      is_mobile: true
